modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/JustMili0/Always-Shield/issues"
license = "MIT"

[[mods]]
modId = "alwaysshield"
version = "${mod_version}"
displayName = "Always Shield"
authors = "JustMili"
description = '''
Removes the obnoxious block delay of the shield, so it works the moment you press Right-Click. No more delay and confusion!
'''
logoFile = "icon.png"

[[dependencies.alwaysshield]]
modId = "forge"
mandatory = true
versionRange = "[${forge_version_range},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.alwaysshield]]
modId = "minecraft"
mandatory = true
versionRange = "[1.21.2,1.21.4]"
ordering = "NONE"
side = "BOTH"
