modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/JustMili0/Always-Shield/issues"
license = "MIT"

[[mods]]
modId = "alwaysshield"
version = "${version}"
displayName = "Always Shield"
authors = "JustMili"
description = '''
Removes the obnoxious block delay of the shield, so it works the moment you press Right-Click. No more delay and confusion!
'''
logoFile = "icon.png"

[[dependencies.alwaysshield]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.alwaysshield]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.alwaysshield]]
modId = "architectury"
type = "required"
versionRange = "[13.0.8,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "alwaysshield.mixins.json"
