modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/JustMili0/Always-Shield/issues"
license = "MIT"

[[mods]]
modId = "alwaysshield"
version = "1.1"
displayName = "Always Shield"
authors = "JustMili"
description = '''
Removes the obnoxious block delay of the shield, so it works the moment you press Right-Click. No more delay and confusion!
'''
logoFile = "icon.png"

[[dependencies.alwaysshield]]
modId = "neoforge"
type = "required"
versionRange = "[${neo_version_range},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.alwaysshield]]
modId = "minecraft"
type = "required"
versionRange = "[${minecraft_version}]"
ordering = "NONE"
side = "BOTH"

[[dependencies.alwaysshield]]
modId = "architectury"
type = "required"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "alwaysshield-neoforge.mixins.json"
